name: starxpand
description: A flutter wrapper around the Star Micronics StarXpand API.
version: 0.0.3
repository: https://github.com/ovatu/starxpand_flutter
homepage: https://ovatu.com/us

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.ovatu.starxpand
        pluginClass: StarxpandPlugin
      ios:
        pluginClass: StarxpandPlugin