plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

group 'com.ovatu.starxpand'
version '1.0-SNAPSHOT'

android {
    compileSdk 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk 21
        targetSdk 36
    }

    namespace 'com.ovatu.starxpand'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation 'com.starmicronics:stario10:1.11.2'
}
